### ISSUE TITLE
Use metadata in data submitted by Ursa Major to modify services

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/fornax#90]
Use the "origin" field in data submitted from Ursa Major, which will indicate whether material is born digital, legacy born digital, or digitized, to modify configurations for the following:

- the AM pipeline where the content will be ingested
- the processing configuration that will be used

**Comment by helrond** [comment]
data will look like:
```
{
  "bag_data": {...},
  "identifier": "1234-235-12312-234135",
  "origin": "aurora"
}
```
